# config.yaml

# Webhook secret for verifying GitHub signatures.
github_webhook_secret: "your_secure_webhook_secret"

# Mapping of GitHub repository full names to their respective deployment configurations.
# Each repository can have multiple servers: server1, server2, etc.
repo_deploy_map:
  "username/sample-backend":
    server1:
      target: "local"
      clone_url: "https://ghp_yourGitHubPAT@github.com/username/sample-backend.git"
      deploy_dir: "/var/www/deployments/sample-backend"
      branch: "main"
      force_rebuild: false
      additional_terminal_tasks:
        - "ping -c 3 google.com"
        - "ls -la"
        - "cd frontend && npm install && npm run build"

    server2:
      target: "remote"
      host: "1.2.3.4"
      user: "ubuntu"
      key_type: "pem"   # or "pkk"
      key_path: "/path/to/ssh-key.pem"
      deploy_dir: "/home/ubuntu/sample-backend"
      branch: "main"
      force_rebuild: true
      additional_terminal_tasks:
        - "cd /home/ubuntu/sample-backend/frontend && npm install && npm run build"
        - "echo 'Finished remote tasks.'"

  # You can add more repos in a similar structure
  # "organization/example-service":
  #   server1: ...
  #   server2: ...

# Docker Compose command options (used by local code in utils.py).
docker_compose_options: "up -d --build --remove-orphans"

# Path to Docker Compose executable.
docker_compose_path: "docker-compose"

# Default Git branch if needed.
git_branch: "main"

# API key for manual deployments.
deploy_api_key: "deploy_API_key_ABC123XYZ"

# API key for listing files and testing commands.
list_files_api_key: "list_files_API_key_DEF456UVW"

# Notifications
notifications:
  slack_webhook_url: ""
  email:
    smtp_server: "smtp.gmail.com"
    smtp_port: 587  # Use 465 for SSL
    use_tls: true   # false if using SSL with port 465
    username: "<your_email_name>@gmail.com"
    password: "example_password_of_gmail_smtp"
    sender_email: "<your_email_name>@gmail.com"
    recipients:
      - "recipient1@gmail.com"
      - "recipient2@gmail.com"
